{% set data = load_setup_py_data() %}

package:
    name: holoviews_sankey
    version: {{ data['version'] }}

source:
    path: ..

build:
    number: {{ GIT_DESCRIBE_NUMBER }}

    script: pip install .

    noarch: python

    preserve_egg_dir: True

    entry_points:
        # Put any entry points (scripts to be generated automatically) here.
        - holoviews_sankey = holoviews_sankey.__main__:main
    
requirements:
    build:
        - python
        - setuptools_scm
        - pandas

    run:
        - python
        - pandas
        - openpyxl
        - bokeh <3.0  # For compatibility with selenium<4.3
        - numpy <2.0  # For compatibility with bokeh<3.0
        - holoviews
        # Selenium (combined with firefox and geckodriver) is
        # required for png export. Version 4.18.1 of
        # selenium had trouble finding 'selenium-manager.exe'
        - selenium <4.3  # Prevent errors running firefox
        - firefox
        - geckodriver

test:
    source_files:
       - holoviews_sankey/examples/Sankey.xlsx

about:
    home: https://github.com/jnettels/holoviews_sankey
    summary: 'Plot sankey flowcharts from spreadheet data with holoviews'
    description: 'Plot sankey flowcharts from spreadheet data with holoviews'
    license: 'MIT'
    license_file: LICENSE
    author: 'Joris Zimmermann'
    author_email: 'joris.zimmermann@stw.de'
